### ISSUE TITLE
Follow XDG Base Directory Specification 

### ISSUE THREAD

**Issue by stnley** [alex-courtis/xlayoutdisplay#11]
I think it would be an improvement if the config file locations followed XDG spec. I like to keep my .dotfiles out of my `$HOME` directory. Perhaps if `$XDG_CONFIG_HOME` is set use that before `$HOME` as the spec indicates? 

I may try my hand a PR but I don't know C++ so it may take some time :smiley:

https://github.com/alex-courtis/xlayoutdisplay/blob/68b8f5811707ea72479b97c00fccf3e9385a790a/src/util.h#L38

**Comment by alex-courtis** [comment]
Created PR https://github.com/alex-courtis/xlayoutdisplay/pull/12

I'd be grateful if you reviewed and tested that branch @stnley

**Comment by stnley** [comment]
@alex-courtis That works perfectly!

**Comment by alex-courtis** [comment]
Thank you @stnley

Merged, with AUR 1.2.0 release incoming.
