### ISSUE TITLE
Build xlayoutdisplay using Docker

### ISSUE THREAD

**Issue by avoidik** [alex-courtis/xlayoutdisplay#13]
Hi,

Just wanted to share a short instruction on how to build it using Docker on Ubuntu for Ubuntu. Probably, a feature request.

Prepare env

```bash
mkdir -p build
docker run --rm -it -v $(pwd)/build:/src --name ubuntu ubuntu:20.04 bash
```

Build it being inside the container

```bash
apt-get update
apt-get install -y build-essential libboost-all-dev libxrandr-dev libxcursor-dev git-core
cd /src
git clone --depth 1 https://github.com/alex-courtis/xlayoutdisplay .
ln -s /usr/lib/x86_64-linux-gnu/libboost_program_options.a /usr/lib/libboost_program_options.a
make
exit
```

No idea how valuable and relevant it is, feel free to close if not at all.

**Comment by alex-courtis** [comment]
That's fantastic, many thanks!

Please submit a PR to add this documentation to `README.md`. If you're not comfortable with a PR, please modify the readme and send it to me for inclusion.

**Comment by avoidik** [comment]
here it is https://github.com/alex-courtis/xlayoutdisplay/pull/14
