### ISSUE TITLE
error: /usr/lib/libboost_program_options.a: No such file or directory

### ISSUE THREAD

**Issue by LumDermaku** [alex-courtis/xlayoutdisplay#15]
Trying to install xlayoutdisplay in ElementaryOS 6.1 causes the following error after executing `make`

> error: /usr/lib/libboost_program_options.a: No such file or directory 
> make: *** [Makefile:17: xlayoutdisplay] Error 1

I already have `libboost-all-dev` package installed ( together with  `build-essential, libxrandr-dev, libxcursor-dev` ) but `libboost_program_options.a` is not found

**Comment by alex-courtis** [comment]
Replaced boost_program_options with getopt and regexes.

Boost was always problematic... there is still no pkg-config after 15 years...

Please pull master and try again. I would be grateful if you could test:
* make gtest
* set some options in .xlayoutdisplay
* set some options on the command line

**Comment by LumDermaku** [comment]
Build worked this time, but the `xlayoutdisplay` is still not being recognized. Am i missing something? I really don't understand the deb-installation. At first there were only steps to manually build the package, then you added a section for installation which to be honest is not as straight forward. I manually put the default `.xlayoutdisplay` file in `/etc/xlayoutdisplay` and then in `$HOME/.xlayoutdisplay` but that didn't help. Maybe it's an elementaryOS-related issue? 

Anyway, in a couple of days/weeks i'll completely switch to either wsl2 with wslg in win11 or in the daily builds of Ubuntu 22.04 since scaling seems to mostly work fine now in both X11 and Wayland ( in a live-boot environment anyway ). In the meantime i'll stick to xrandr/autorandr.

**Comment by alex-courtis** [comment]
> At first there were only steps to manually build the package, then you added a section for installation which to be honest is not as straight forward

What is the issue? I realise I forgot the `sudo make install` step, which I will add now.

> xlayoutdisplay is still not being recognized

Is there an error shown when you run it? Is the `.xlayoutdisplay` file just not being found?
