### ISSUE TITLE
The font does scale back when disconnected from monitor

### ISSUE THREAD

**Issue by abhixec** [alex-courtis/xlayoutdisplay#18]
I use arch+xmonad on Thinkpad X1E gen1, recently discovered this tool(just what I needed to scale the apps for a 5k display but the problem is when I disconnect from the monitor on my laptop it still remains scaled up. Is there a setting I need to ensure that it scales back to original when on laptop?
Thanks!

**Comment by alex-courtis** [comment]
Are you successfully re-running after disconnecting?

Unfortunately, after the dpi change, some applications won't scale themselves immediately. They will need to, say, restart or open a new window.

If you'd like full automation and resizing, you could move to Sway (wayland) and use [way-displays](https://github.com/alex-courtis/way-displays).

**Comment by abhixec** [comment]
Yes, but it still shows up big.
Since I use xmonad and it still depends on X, wayland isn't an option for me A.T.M.

**Comment by alex-courtis** [comment]
That is an unfortunate restriction of X11 apps. I don't think it is possible for them to be notified of dpi changes, they would have to poll.

I recently moved from dwm to sway. It was difficult at first, but I have successfully adjusted my workflow and am productive now. That's what motivate me to write way-displays ;)
