### ISSUE TITLE
Start `xlayoutdisplay` as server/daemon

### ISSUE THREAD

**Issue by rxt30** [alex-courtis/xlayoutdisplay#19]
`way-displays` can be started as a server/daemon, as stated in the [Readme.md](https://github.com/alex-courtis/way-displays#usage). Is there a similiar function for `xlayoutdisplay`?

I tried to start `xlayoutdipslay` as a server as described for `way-displays`, but it doesn't seem to offer the same functionality, as it simply quits after printing the usual information.

**Comment by alex-courtis** [comment]
No. `xlayoutdisplay` runs once to configure the displays then exits.

It could be possible to achieve this functionality by reacting to display hotplug events, however there is no easy or obvious way to do this in an X11 environment.

I'm very open to any ideas you might have as to how we could achieve this functionality.

**Comment by rxt30** [comment]
Discovered a possible solution for hot-plugging with `udev`, but this can be more seen as some suggestions and is not as pretty as implementing a daemon like function.

Simply create a `udev`-rule with the following content (for example in `/etc/udev/rules.d/99-monitor.rules`) with the following content:
```
ACTION=="change", SUBSYSTEM=="drm", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/run/user/1000/gdm/Xauthority", RUN+="/usr/bin/xlayoutdisplay"
```
**Important Note**
`XAUTHORITY` may be set to a different location by your display manager, please check with `printenv XAUTHORITY`

More information can be found [here](https://wiki.archlinux.org/title/Udev#Execute_when_HDMI_cable_is_plugged_in_or_unplugged).

Sadly i didn't discovered a `udev`-event for the laptop lid yet.

**Comment by alex-courtis** [comment]
That looks promising.

> I also don't know if there could be any problems if multiple X11-Sessions are running

It should be possible; `$DISPLAY` could be set to that of the X11 session. Rather than running `/usr/bin/xlayoutdisplay` directly, a script could be called that invokes xlayoutdisplay for each session's `$DISPLAY`.

> `ENV{XAUTHORITY}="/run/user/1000/gdm/Xauthority"`

This may not work, as that session is the login manager's session (VTNR 0), not the user's session, likely VTNR 1. `/usr/bin/xlayoutdisplay` would be run by root and would not see `~/.xlayoutdisplay`, and may not be able to set the modes etc.

Workarounds:
* `OWNER="username"`
* Use `/etc/xlayoutdisplay`
* `ENV{XAUTHORITY}="/home/username/Xauthority"`

> Sadly i didn't discovered a udev-event for the laptop lid yet.

There is none. Experimentation has shown that `/proc/acpi/button/lid/...` is not pollable for changes and would need to be constantly read.

libinput is used by `way-displays`: it is able to monitor and allows the user to poll for changes.

**Comment by alex-courtis** [comment]
I'd be grateful if you could conduct an experiment to prove the concept @rxt30 :

Create and test a rule with some of the above changes. You could hardcode `DISPLAY` and `XAUTHORITY` for the user's known session.

The most interesting result would be plugging when the user's session is not active: login manager, another user sessior, tty etc.

**Comment by alex-courtis** [comment]
> I tested the concept as a daily driver for the last two weeks now and so far i have been really happy with that solution.

Great news, especially standby.

> I used `gdm` as a display manager/login manager, that's why the `XAuthority`-Env points to a file outside the home directory.
> I don't think that this is in our scope, as the `XAuthority`-variable gets set by the display manager.
> However, using a different display manager may solve this problem as the `Xauthority`-variable could then be set to the home directory, so that a user can use the `.xlayoutdisplay` inside their home directory.

That's OK. It could be left to the user to fill in if they are using gdm or similar.

Can you please create a PR?
- sample `.rules` file
- draft README directions on how to configure / install the rules

I think it's best that we don't install the rules for now; we leave that to the user, as they can't be one-size-fits-all.

After that we can:
- decide how to distribute the sample rules (may as well do .xlayoutdisplay at the same time)
- finish README
