### ISSUE TITLE
suggestion : don't change anything when run with no arguments

### ISSUE THREAD

**Issue by fenugrec** [alex-courtis/xlayoutdisplay#27]
I ran just `xlayoutdisplay` with no args expecting some usage info and general help, and it went ahead and messed up my config.
Still haven't recovered yet, DPI is weird, half the applications don't scale well...

Suggest either modifying default behaviour to NOT do this, or at the very least, create a backup of current config...
Or prompt user to press enter to continue with default behaviour (and an extra switch, e.g. `-y` or whatever, to skip prompt - if any args are given, unnecessary to prompt)

[EDIT - was able to restore most of my settings, but needed to restart X / reboot for full effect]

**Comment by alex-courtis** [comment]
Thanks for the suggestion. That would be more user friendly.

Unfortunately we can't do that now, as that would break most users, who simply call `xlayoutdisplays` in their `.xinitrc`

**Comment by fenugrec** [comment]
is there not a way to detect whether xlayoutdisplay is run from an interactive shell vs an init script ?

**Comment by alex-courtis** [comment]
> is there not a way to detect whether xlayoutdisplay is run from an interactive shell vs an init script ?

That's a good suggestion, however that will break users who simply invoke `xlayoutdisplay` from the command line after, say, plugging in a monitor.
