### ISSUE TITLE
Does not make in Kali Linux (Debian), unable to locate `libprocps.ps` and `proc/readproc.h` not found.

### ISSUE THREAD

**Issue by anoduck** [alex-courtis/xlayoutdisplay#28]
Attempted two methods of compilation: 1) via standard execution of `make`, 2) via use of docker to build. Both methods failed with `src/xutil.cpp:17:10: fatal error: proc/readproc.h: No such file or directory`. The first method (standard make) also was unable to locate `libprocps.pc`, which does not appear to be included in the `libprocps7` package.

**Comment by alex-courtis** [comment]
Kali, and apparently most other debian distributions do not include libproc headers. They are present in the `libprocps-dev` package.

I've added the necessary packages, with pkg-config, to the docker container.

I'd be grateful if you attempted docker build with the following additions: https://github.com/alex-courtis/xlayoutdisplay/pull/29/files

**Comment by anoduck** [comment]
@alex-courtis I am learning that Kali is not as cool as Debian to develop on. Kali doesn't provide a `libprocps-dev` package. Which means the only way of acquiring the needed libraries is building libprocps from source. Also, Kali is still using libprocps version 7. 

It built smooth as butter in docker, and now that I know, all is needed is for me to acquire libprocps source for my local system. I am good to go. 

Thanks for all the help Alex!
