### ISSUE TITLE
error in make

### ISSUE THREAD

**Issue by magruca** [alex-courtis/xlayoutdisplay#3]
Hi--

I got cmake to run successfully after some trail and error:

$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mgruca/dowell/xlayoutdisplay/build

But unfortunately now it's failing on the build and seems to be missing a header file:

[  5%] Building CXX object CMakeFiles/xlayoutdisplay.dir/src/calculations.cpp.o
In file included from /home/mgruca/dowell/xlayoutdisplay/src/Output.h:19,
                 from /home/mgruca/dowell/xlayoutdisplay/src/calculations.h:20,
                 from /home/mgruca/dowell/xlayoutdisplay/src/calculations.cpp:16:
/home/mgruca/dowell/xlayoutdisplay/src/Mode.h:19:10: fatal error: X11/extensions/Xrandr.h: No such file or directory
 #include <X11/extensions/Xrandr.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/xlayoutdisplay.dir/build.make:63: CMakeFiles/xlayoutdisplay.dir/src/calculations.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/xlayoutdisplay.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Any suggestions? I'm working on Fedora29.

Thanks!

**Comment by alex-courtis** [comment]
Hello

Xrandr.h is owned (on my arch system) by [libxrandr](https://www.archlinux.org/packages/extra/x86_64/libxrandr/). This is needed for [xrandr](https://wiki.archlinux.org/index.php/Xrandr), an xlayoutdisplay requirement.

Sorry I was so late with the this; watch settings...
