### ISSUE TITLE
Support for LVDS laptop screens

### ISSUE THREAD

**Issue by Ampnbsp** [alex-courtis/xlayoutdisplay#33]
I have an old laptop with LVDS screen, so when I use the program with the closed lid it doesn't count this state.

**Comment by alex-courtis** [comment]
To enable lid detection we need:
1. Name of the display: hardcoded to `""eDP.*"`
2. State of the lid: looks for `/proc/acpi/button/lid/.*/state`

## 1 Name
We can add configuration for name as per the wayland version of this tool way-displays: [LAPTOP_DISPLAY_PREFIX: 'eDP](https://github.com/alex-courtis/way-displays/blob/master/doc/CONFIGURATION.md#laptop_display_prefix)

What's the name of the display e.g.
```
:; ./xlayoutdisplay
eDP1 active 31cm/17cm 2560x1440+0+0 60Hz
*+ 2560x1440 60Hz
  !2560x1440 60Hz
...
```

## 2 State

Is there a state file for your lid? I see:

```sh
:; find /proc/acpi/button/lid
/proc/acpi/button/lid
/proc/acpi/button/lid/LID
/proc/acpi/button/lid/LID/state
:; cat /proc/acpi/button/lid/LID/state
state:      open
```
