### ISSUE TITLE
How to use this with 1.25x1.25 scaling?

### ISSUE THREAD

**Issue by ostenning** [alex-courtis/xlayoutdisplay#4]
Hi, I'm attempting to have 2 monitors with a custom scaling factor:

eDP1, 1440p screen at 1.25x1.25 scaling factor
HDMI1, 1080p screen at 1x1 scaling factor

With no overlap.

Basically I am using the HDPI guide from the arch wiki for my laptop screen, but I want a standard 1080p external monitor to use also. https://wiki.archlinux.org/index.php/HiDPI

Is this possible?

**Comment by FFY00** [comment]
I am also interested in using this with scaling.

**Comment by infin1tyy** [comment]
Likewise.

**Comment by alex-courtis** [comment]
Two workarounds:

1. Copypasta and modify the xrandr command that xlayoutdisplay uses
2. Use something like arandr to build an xrandr command line

Both are poor options. We can do better:

We cannot have multiple dpis, however we can have the scale relative to the primary monitor. I'm imagining adding a list of scales similar to order e.g. `-s 1 -s 0.8` for the above example. That would come out to something like:
```
xrandr
  --dpi 120 \
  --output eDP1 --scale 1 --primary ... \
  --output HDMI1 --scale 0.8 ...
```

Very happy to accept PRs and assist in getting a branch working.
