### ISSUE TITLE
CMake Error: The following variables NOT_FOUND: X11_Xcursor_LIB / X11_Xrandr_LIB

### ISSUE THREAD

**Issue by benzkji** [alex-courtis/xlayoutdisplay#5]
after having installed boost-dev libraries and googletest, this is where I am currently stuck. Any help welcome.

**Comment by blkmlk** [comment]
sudo apt-get install libxrandr-dev
sudo apt-get install libxcursor-dev

**Comment by benzkji** [comment]
thank you! will test.
