### ISSUE TITLE
Setting refresh rate with argument?

### ISSUE THREAD

**Issue by fpaskali** [alex-courtis/xlayoutdisplay#8]
Is it possible to set the refresh rate of the screen with xlayoutdisplay, without modifying xrandr output?

**Comment by alex-courtis** [comment]
It is not currently possible to do this; the refresh rate is set to the highest available for the monitor's preferred resolution.

I do accept pull requests if you'd like to build this feature.

**Comment by fpaskali** [comment]
Thank you, for the answer. I will try, however I do not have much C++ experience.
